spring:
  application:
    name: christmas-api

  datasource:
    url: jdbc:mysql://localhost:3306/christmas
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  mybatis:
    type-aliases-package: com.christmas.api.infrastructure.repository.persistence.mapper


